import ContactIcons from "../components/ContactIcons";
export const columns = [
  {
    field: "devoteeName",
    headerName: "Name",
    minWidth: 150,
    sortable: true,
    flex: 1,
  },
  {
    field: "mentorName",
    headerName: "Mentor Name",
    minWidth: 150,
    sortable: true,
    flex: 1,
  },
  {
    field: "phoneNumber",
    headerName: "Contact",
    minWidth: 100,
    flex: 1,
    renderCell: (params) => <ContactIcons params={params} />,
  },
  { field: "foeLevel", headerName: "FOE Level", minWidth: 120, sortable: true, flex:1 },
  {
    field: "chantingRounds",
    headerName: "Chanting Rounds",
    minWidth: 160,
    flex: 1,
    sortable: true,
  },
];

export const rows = [
  {
    id: 1,
    devoteeName: "Radharani",
    mentorName: "Guruji",
    phoneNumber: "9876543210",
    foeLevel: "Level 3",
    chantingRounds: 16,
  },
  {
    id: 2,
    devoteeName: "Gopal Krishna",
    mentorName: "Prabhuji",
    phoneNumber: "9123456780",
    foeLevel: "Level 2",
    chantingRounds: 12,
  },
  {
    id: 3,
    devoteeName: "Meera Devi",
    mentorName: "Guruji",
    phoneNumber: "9988776655",
    foeLevel: "Level 1",
    chantingRounds: 8,
  },
  {
    id: 4,
    devoteeName: "Rama Das",
    mentorName: "Prabhuji",
    phoneNumber: "9012345678",
    foeLevel: "Level 2",
    chantingRounds: 14,
  },
  {
    id: 5,
    devoteeName: "Sita Devi",
    mentorName: "Guruji",
    phoneNumber: "9876501234",
    foeLevel: "Level 3",
    chantingRounds: 16,
  },
  {
    id: 6,
    devoteeName: "Bhakta Ananda",
    mentorName: "Prabhuji",
    phoneNumber: "9988123456",
    foeLevel: "Level 1",
    chantingRounds: 10,
  },
  {
    id: 7,
    devoteeName: "Vasudev",
    mentorName: "Guruji",
    phoneNumber: "9999001122",
    foeLevel: "Level 2",
    chantingRounds: 12,
  },
  {
    id: 8,
    devoteeName: "Rukmini",
    mentorName: "Guruji",
    phoneNumber: "9090909090",
    foeLevel: "Level 3",
    chantingRounds: 16,
  },
  {
    id: 9,
    devoteeName: "Nimai Das",
    mentorName: "Prabhuji",
    phoneNumber: "9123456789",
    foeLevel: "Level 2",
    chantingRounds: 15,
  },
  {
    id: 10,
    devoteeName: "Lalita Devi",
    mentorName: "Guruji",
    phoneNumber: "9234567890",
    foeLevel: "Level 1",
    chantingRounds: 9,
  },
  {
    id: 11,
    devoteeName: "Haridas",
    mentorName: "Prabhuji",
    phoneNumber: "9876540000",
    foeLevel: "Level 3",
    chantingRounds: 16,
  },
  {
    id: 12,
    devoteeName: "Kirtan Bhakta",
    mentorName: "Guruji",
    phoneNumber: "9000012345",
    foeLevel: "Level 2",
    chantingRounds: 13,
  },
  {
    id: 13,
    devoteeName: "Yashoda Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9812312345",
    foeLevel: "Level 1",
    chantingRounds: 7,
  },
];

export const panathurData = [
  {
    id: 1,
    devoteeName: "Madhava Das",
    mentorName: "Guruji",
    phoneNumber: "9876543211",
    foeLevel: "Level 3",
    chantingRounds: 15,
  },
  {
    id: 2,
    devoteeName: "Radhika Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9123456781",
    foeLevel: "Level 2",
    chantingRounds: 10,
  },
  {
    id: 3,
    devoteeName: "Govinda Das",
    mentorName: "Guruji",
    phoneNumber: "9988776656",
    foeLevel: "Level 3",
    chantingRounds: 8,
  },
  {
    id: 4,
    devoteeName: "Keshava Das",
    mentorName: "Prabhuji",
    phoneNumber: "9012345679",
    foeLevel: "Level 2",
    chantingRounds: 14,
  },
  {
    id: 5,
    devoteeName: "Govinda Das",
    mentorName: "Guruji",
    phoneNumber: "9988776656",
    foeLevel: "Level 1",
    chantingRounds: 8,
  },
  {
    id: 6,
    devoteeName: "Keshav",
    mentorName: "Prabhuji",
    phoneNumber: "9012345679",
    foeLevel: "Level 2",
    chantingRounds: 14,
  },
  {
    id: 7,
    devoteeName: "Lakshmi Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9123456782",
    foeLevel: "Level 2",
    chantingRounds: 12,
  },
  {
    id: 8,
    devoteeName: "Narayan Das",
    mentorName: "Guruji",
    phoneNumber: "9988776657",
    foeLevel: "Level 1",
    chantingRounds: 9,
  },
];

export const whitefieldData = [
  {
    id: 1,
    devoteeName: "Vishnu Das",
    mentorName: "Guruji",
    phoneNumber: "9876543222",
    foeLevel: "Level 3",
    chantingRounds: 16,
  },
  {
    id: 2,
    devoteeName: "Lakshmi Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9123456782",
    foeLevel: "Level 2",
    chantingRounds: 12,
  },
  {
    id: 3,
    devoteeName: "Narayan Das",
    mentorName: "Guruji",
    phoneNumber: "9988776657",
    foeLevel: "Level 1",
    chantingRounds: 9,
  },
  {
    id: 4,
    devoteeName: "Padma Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9012345680",
    foeLevel: "Level 2",
    chantingRounds: 13,
  },
  {
    id: 5,
    devoteeName: "Govinda Das",
    mentorName: "Guruji",
    phoneNumber: "9988776656",
    foeLevel: "Level 1",
    chantingRounds: 8,
  },
  {
    id: 6,
    devoteeName: "Keshav",
    mentorName: "Prabhuji",
    phoneNumber: "9012345679",
    foeLevel: "Level 2",
    chantingRounds: 14,
  },
  {
    id: 7,
    devoteeName: "Tulasi Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9123456783",
    foeLevel: "Level 2",
    chantingRounds: 11,
  },
];

export const AECSData = [
  {
    id: 1,
    devoteeName: "Hari Das",
    mentorName: "Guruji",
    phoneNumber: "9876543233",
    foeLevel: "Level 3",
    chantingRounds: 16,
  },
  {
    id: 2,
    devoteeName: "Tulasi Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9123456783",
    foeLevel: "Level 3",
    chantingRounds: 11,
  },
  {
    id: 3,
    devoteeName: "Chaitanya Das",
    mentorName: "Guruji",
    phoneNumber: "9988776658",
    foeLevel: "Level 1",
    chantingRounds: 7,
  },
  {
    id: 4,
    devoteeName: "Bhakti Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9012345681",
    foeLevel: "Level 2",
    chantingRounds: 14,
  },
  {
    id: 5,
    devoteeName: "Govinda Das",
    mentorName: "Guruji",
    phoneNumber: "9988776656",
    foeLevel: "Level 1",
    chantingRounds: 8,
  },
  {
    id: 6,
    devoteeName: "Lakshmi Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9123456782",
    foeLevel: "Level 2",
    chantingRounds: 12,
  },
  {
    id: 7,
    devoteeName: "Narayan Das",
    mentorName: "Guruji",
    phoneNumber: "9988776657",
    foeLevel: "Level 1",
    chantingRounds: 9,
  },
  {
    id: 8,
    devoteeName: "Padma Devi",
    mentorName: "Prabhuji",
    phoneNumber: "9012345680",
    foeLevel: "Level 2",
    chantingRounds: 13,
  },
  {
    id: 9,
    devoteeName: "Govinda Das",
    mentorName: "Guruji",
    phoneNumber: "9988776656",
    foeLevel: "Level 1",
    chantingRounds: 8,
  },
  {
    id: 10,
    devoteeName: "Keshav",
    mentorName: "Prabhuji",
    phoneNumber: "9012345679",
    foeLevel: "Level 2",
    chantingRounds: 14,
  },
];
